<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018-10-29
 * Time: 14:19
 */

namespace app\libs\exception;


use app\index\controller\SignController;
use Exception;
use think\exception\Handle;

class ExceptionHandler extends Handle
{
    private $code;
    private $msg;
    private $errorCode;
    private $errorMsg;

    public function render(Exception $e)
    {
        if($e instanceof BaseException){
            $this->code = $e->code;
            $this->msg = $e->msg;
            $this->errorCode = $e->errorCode;
            $this->errorMsg = $e->errorMsg;
        } else {
            if (config('app_debug')){
                return parent::render($e); // TODO: Change the autogenerated stub
            } else {
                $this->code = 400;
                $this->msg = 'unknown server error';
                $this->errorCode = '9999';
                $this->errorMsg = '未知的服务器错误';
            }
        }
        //$out['errorCode'] = $this->errorCode;
        //$out['errorMsg'] = $this->errorMsg;
        $out['return_code'] = $this->code;
        $out['return_msg'] = $this->msg;
        $out['data'] = '';
        $out['timestamp'] = strval(time());
        $out['requestUrl'] = 'http://'.$_SERVER['SERVER_NAME'].$_SERVER['REQUEST_URI'];
        //必要时，此处可以添加签名字段
        $key = config('secure.xiaochengxukey');
        $sign = SignController::createSign($out,$key);
        $out['sign'] = $sign;
        setLogs('request_error',json_encode($out,JSON_UNESCAPED_UNICODE));
        return json($out);
    }





}